### ISSUE TITLE
IViewInjector new methods

### ISSUE THREAD

**Issue by fcannizzaro** [MEiDIK/SlimAdapter#1]
Can you add some methods ?

like
```java
injector.alpha(int id, float alpha);

injector.visible(int id, boolean condition);

injector.invisible(int id, boolean condition);

injector.gone(int id, boolean condition);
```

Great library 👍

**Comment by linisme** [comment]
Thanks for feedback～

I will add lots of common methods in the coming version, but maybe still can not consider every single method...

so, maybe these 2 way will be helpful:

1. Extends the CustomViewInjector to match you needs, the docs & example is on the way.
1. Fork & Contribute your code to improve this lib

Thanks again#

**Comment by fcannizzaro** [comment]
ok #2 submitted :)
