### ISSUE TITLE
Feature: Loading ViewType

### ISSUE THREAD

**Issue by llleodeleon** [MEiDIK/SlimAdapter#12]
I use adapters alongside the recyclerView to load more data and display a progress bar while waiting for the response. Do you guys have suggestions on how to do that using the SlimAdapter? If it's possible to accomplish it I'm changing all my recycler views 😀

**Comment by miszmaniac** [comment]
Why not style element as usual with .register() and add end remove last(or first) element in items?

**Comment by linisme** [comment]
thanks for feedback,,

branch 2.x provider an ex module to support more power feature, containing loading more

but it still under dev,,so the api may change,,
