### ISSUE TITLE
QUESTION: how can i update just a single section data.

### ISSUE THREAD

**Issue by yesidlazaro** [MEiDIK/SlimAdapter#15]
hi, thanks your lib looks nice, but i looking for a example for how i can update just the data for a single section , for example i have 3 sections and 2 of them are loaded from database but one is loaded from internet , so i need to know how update the last one section when i get the data form internet without reload the others 2 sections. 

is this posible ?

**Comment by linisme** [comment]
sorry for reply so late，，

you mean you want the “add” data feature？ maybe you could extract the current data from the adapter and merge it with the internal data, then update the adapter again?

here is the api

```
    public List getData();
```
