### ISSUE TITLE
List keep getting duplicated

### ISSUE THREAD

**Issue by Saurabh682** [MEiDIK/SlimAdapter#20]
Hi,
First of all thanks for the the SlimAdapter.
I am facing an issue which I am sure is not a big deal. But I am a newbie so couldn't find the wayout.

The Issue- 
1) My RecyclerView list gets an addon of a whole set of items everytime I call my activity. That is where I got stuck.
2) I couldn't import integer value so for the time being I converted it into string but is there a better option for it.

Thanks

**Comment by linisme** [comment]
Thanks～

issue 2 u could try to use “Integer” install of “int”， and issue 1 may be caused by data set duplicated，could u show me some code？
