### ISSUE TITLE
请问能提供下拉刷新功能吗？（How to pull to refresh  ， sir ？）

### ISSUE THREAD

**Issue by hanshou101** [MEiDIK/SlimAdapter#26]
大佬你好，
我好像只找到了 loadMore 下拉加载功能。

并没有看见下拉刷新，请问这个功能在当前版本存在吗 （Is pull_to_refresh available? ）

**Comment by linisme** [comment]
目前不提供下拉刷新功能，建议使用官方的下拉刷新库SwipeRefreshLayout，通过组合的方式也更灵活处理
