### ISSUE TITLE
register layout contain recyclerview

### ISSUE THREAD

**Issue by mrzslr** [MEiDIK/SlimAdapter#4]
how i can register for a layout contain recyclerview that it want to be filled ?
and how to pass data list ?any method or somethings else?
in other word ReyclerView in RecyclerView.

**Comment by linisme** [comment]
i have not test for it, but i provide a method in viewinjector name “.adapter”，u could try it

if not work, u could use the other method ".with" to get the inner recycleview, then do what u wants.
