### ISSUE TITLE
可以新增些属性？

### ISSUE THREAD

**Issue by AndMy** [MEiDIK/SlimAdapter#5]
上拉、下拉更新数据、addheadview、addfootview

**Comment by linisme** [comment]
多谢反馈～
由于SlimAdapter定位Slim，而并不想成为一个Super，所以未提供相应的功能。
目前工作比较忙，还没有时间进一步设计，后续的开发计划提供一个功能增强模块，提供你所说的这些功能，如果你有时间也可以帮忙设计开发一下～
多谢～
