### ISSUE TITLE
Register with view factory instead of layout id

### ISSUE THREAD

**Issue by FredJul** [MEiDIK/SlimAdapter#7]
Hi,

First of all thank you for this nice lib, I really like the API!

However, in some cases you really just need a single view into your adapter. In that particular case, being forced to create an layout file with this single view and have to inflate it is not really performant, it would be much more efficient to be able to provide a view factory or any similar concept to the register method.

**Comment by linisme** [comment]
Thanks for suggestion, it will be considered by next version~
