### ISSUE TITLE
SlimInjector IllegalArgumentException (lambda)

### ISSUE THREAD

**Issue by fcannizzaro** [MEiDIK/SlimAdapter#8]
Using **lambda** instead of **anonymous class** make it crash.

```java8
(Episode episode, IViewInjector view) -> {                    
  // code
})
```

instead of

```java
new SlimInjector<Episode>() {
    @Override
    public void onInject(Episode episode, IViewInjector view) {
        // code
    }
})
```

**Comment by miszmaniac** [comment]
Sadly you can't use it with lambda as there is no way to get type information after code is compiled.
We've made fork https://github.com/kubatatami/SlimAdapter where we added second parameter with class in register method, just to make it work with lambda.

**Comment by linisme** [comment]
@miszmaniac thanks again for your solution
