### ISSUE TITLE
Can't have fastscroll

### ISSUE THREAD

**Issue by FredJul** [MEiDIK/SlimAdapter#9]
I didn't find any way to have a fastscroll with your API. I like to use https://github.com/FutureMind/recycler-fast-scroll but I can't mix the two libraries due to the fact that SlimAdapter is hidden (and so I can't override it and make it implements SectionTitleProvider.

Having a public constructor instead of a SlimAdapter.create() method would certainly solve that issue.

**Comment by linisme** [comment]
thanks for feedback..

hiding the constructor is for forcing to use the fluent calls,  but your case makes sense... i will solve the question or maybe you could fork to contribute your help~

**Comment by miszmaniac** [comment]
I had similar problem and ended up using recyclerView.Adapter wrapper, and delegated methods like this:
```java

    private final SlimAdapter slimAdapter;

    public MyNewAdapter(SlimAdapter slimAdapter) {
        this.slimAdapter = slimAdapter;
    }

    @Override
    public int getItemViewType(int position) {
        return slimAdapter.getItemViewType(position);
    }

    @Override
    public SlimViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        return slimAdapter.onCreateViewHolder(parent, viewType);
    }

    @Override
    public void onBindViewHolder(SlimViewHolder holder, int position) {
        slimAdapter.onBindViewHolder(holder, position);
    }

    @Override
    public int getItemCount() {
        return slimAdapter.getItemCount();
    }`

**Comment by FredJul** [comment]
Well, that's a smart and certainly working solution, thanks for sharing it. 

However I think SlimAdapter would gain to propose a very simple and documented solution. Could be by allowing to override the SlimAdapter class, providing a abstract SlimAdapterWrapper, or finding another solution (right now I don't have better idea). Not sure of what you prefer to officially include into SlimAdapter.

**Comment by linisme** [comment]
sorry for reply so late..i am a little too busy in my new project recently...

u could override the SlimAdapter class now to merge with other features, any better idea u found please let me know, sorry again

**Comment by midhilajm** [comment]
we have same problem how to solve?
